version: "3"

services:
  db:
    image: postgres:latest
    container_name: schoolplatform_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  db:
    driver: bridge

volumes:
  db_data:


